name: CI-CD Pipeline with GitOps

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run basic tests
        run: |
          python -m py_compile app/app.py


  docker-build-push:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: build-test

    outputs:
      image_tag: ${{ steps.set-tag.outputs.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        id: set-tag
        run: |
          echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=v${{ github.run_number }}" 
          echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-python-app:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-python-app:${{ env.IMAGE_TAG }}


  update-gitops:
    name: Update GitOps Repo
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: Gokulk-306/devops-app-gitops
          token: ${{ secrets.GH_PAT }}

      - name: Update deployment.yaml
        run: |
          sed -i "s|^ *image: .*|          image: ${{ secrets.DOCKERHUB_USERNAME }}/devops-python-app:${{ needs.docker-build-push.outputs.image_tag }}|" k8s/deployment.yaml

      - name: Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add k8s/deployment.yaml
          git commit -m "GitOps Update: Deploy image ${{ needs.docker-build-push.outputs.image_tag }}" || echo "No changes"
          git push
